#requires -version 5.1
[CmdletBinding()]
param([switch]$NoPause)
$ErrorActionPreference = 'Stop'
$workshopRoot = Split-Path -Parent $PSScriptRoot
$referenceRoot = Join-Path $workshopRoot 'reference_catalog'
$logRoot = Join-Path $workshopRoot 'logs'
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$runRoot = Join-Path $logRoot "inventory_local_sources_$timestamp"
$logPath = Join-Path $runRoot 'inventory_local_sources.log.txt'
$csvPath = Join-Path $referenceRoot 'detailed_resource_inventory.csv'
$mdPath = Join-Path $referenceRoot 'detailed_resource_inventory.md'
$zipPath = Join-Path $runRoot "inventory_local_sources_$timestamp.zip"
New-Item -ItemType Directory -Force -Path $referenceRoot, $runRoot | Out-Null
function Write-Log { param([string]$Message) $line = "[{0}] {1}" -f (Get-Date -Format 'u'), $Message; $line | Tee-Object -FilePath $logPath -Append }
function Get-TitleGuess { param([string]$Name) $base = [System.IO.Path]::GetFileNameWithoutExtension($Name); $base = $base -replace '[_]+', ' '; $base = $base -replace '\s+', ' '; $base.Trim() }
function Get-ResourceRole { param([string]$RelativePath) switch -Regex ($RelativePath) { '^downloaded_sources\\OpenAI' { 'primary_reference'; break } '^downloaded_sources\\OpenAI_Academy' { 'primary_reference'; break } '^downloaded_sources\\Code\.org' { 'teaching_reference'; break } '^downloaded_sources\\ISTE\+ASCD' { 'teaching_reference'; break } '^downloaded_sources\\Google' { 'tool_reference'; break } '^downloaded_sources\\Machine_Learning_for_Kids' { 'activity_reference'; break } '^reference_catalog\\' { 'catalog_artifact'; break } '^workshop_pack\\slides\\' { 'slide_asset'; break } '^workshop_pack\\worksheets\\' { 'worksheet_asset'; break } '^workshop_pack\\project_sheets\\' { 'project_asset'; break } '^workshop_pack\\scripts\\' { 'facilitator_asset'; break } '^workshop_pack\\' { 'workshop_asset'; break } default { 'supporting_asset' } } }
function Get-ReuseStatus { param([string]$RelativePath) switch -Regex ($RelativePath) { '^downloaded_sources\\' { 'validated_reference_candidate'; break } '^reference_catalog\\official_' { 'existing_catalog'; break } '^reference_catalog\\download_results' { 'existing_download_log'; break } '^workshop_pack\\learning_plan_ai_chatgpt_session\.html' { 'partial_reuse'; break } '^workshop_pack\\parent_guardian_setup_flow\.html' { 'partial_reuse'; break } '^workshop_pack\\tool_walkthroughs\.html' { 'partial_reuse'; break } '^workshop_pack\\facilitator_slides\.html' { 'partial_reuse'; break } '^workshop_pack\\' { 'example_or_partial_reuse'; break } default { 'review_required' } } }
$resourceFiles = Get-ChildItem -Path (Join-Path $workshopRoot 'downloaded_sources'), (Join-Path $workshopRoot 'reference_catalog'), (Join-Path $workshopRoot 'workshop_pack') -Recurse -File | Sort-Object FullName
$index = 0
$rows = foreach ($file in $resourceFiles) { $index += 1; $relative = $file.FullName.Substring($workshopRoot.Length + 1); $section = $relative.Split('\')[0]; $provider = if ($relative.Contains('\')) { $relative.Split('\')[1] } else { '' }; [pscustomobject]@{ inventory_id = ('RES-{0:000}' -f $index); section = $section; provider_or_pack = $provider; relative_path = $relative; file_type = $file.Extension.TrimStart('.').ToLowerInvariant(); title_guess = Get-TitleGuess -Name $file.Name; source_role = Get-ResourceRole -RelativePath $relative; reuse_status = Get-ReuseStatus -RelativePath $relative; notes = if ($relative -match 'Teen_AI_Literacy_Blueprint|What is ChatGPT|How do I create a good prompt|learning_plan_ai_chatgpt_session|parent_guardian_setup_flow|tool_walkthroughs') { 'High-value item for learning-system expansion.' } else { '' } } }
$rows | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
$sectionCounts = $rows | Group-Object section | Sort-Object Name
$providerCounts = $rows | Where-Object { $_.section -eq 'downloaded_sources' } | Group-Object provider_or_pack | Sort-Object Count -Descending
$highValue = $rows | Where-Object { $_.notes }
$sectionTable = ($sectionCounts | ForEach-Object { "| $($_.Name) | $($_.Count) |" }) -join "`r`n"
$providerTable = ($providerCounts | ForEach-Object { "| $($_.Name) | $($_.Count) |" }) -join "`r`n"
$highValueTable = ($highValue | ForEach-Object { "| $($_.relative_path) | $($_.source_role) | $($_.reuse_status) | $($_.notes) |" }) -join "`r`n"
$md = @"
# Detailed Resource Inventory

Generated by `inventory_local_sources.ps1` on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').

## Scope

- Workshop root: `$workshopRoot`
- Included folders:
  - `downloaded_sources`
  - `reference_catalog`
  - `workshop_pack`

## Summary Counts

| Section | File Count |
| --- | ---: |
$sectionTable

## Downloaded Source Providers

| Provider | File Count |
| --- | ---: |
$providerTable

## High-Value Existing Files

| Relative Path | Role | Reuse Status | Notes |
| --- | --- | --- | --- |
$highValueTable

## Crosswalk Notes

- `workshop_pack\learning_plan_ai_chatgpt_session.html` already provides a 90-minute session outline and can seed the expanded learning plan.
- `workshop_pack\parent_guardian_setup_flow.html` covers family-side setup but needs updating for current event framing and safe-use specifics.
- `workshop_pack\tool_walkthroughs.html` includes prompt examples and walkthrough structure that can feed beginner activities.
- `workshop_pack\facilitator_slides.html` contains slide-ready topic blocks and can feed the slide candidate matrix.
- The OpenAI and OpenAI Academy cached references are the primary current references for ChatGPT, prompting, memory, projects, and teaching-safe use.
"@
$md | Set-Content -Path $mdPath -Encoding UTF8
Write-Log "inventory_csv=$csvPath"
Write-Log "inventory_md=$mdPath"
Compress-Archive -Path @($csvPath, $mdPath, $logPath) -DestinationPath $zipPath -Force
Write-Log "zip_bundle=$zipPath"
Write-Log "resource_file_count=$($rows.Count)"
Write-Log 'COMPLETE'
Write-Host "Inventory complete.`nCSV: $csvPath`nMD : $mdPath`nZIP: $zipPath" -ForegroundColor Green
if (-not $NoPause) { Write-Host "`nPress ENTER to exit..." -ForegroundColor Yellow; [void][System.Console]::ReadLine() }
